---
kind: pipeline
name: friend

steps:
  - name: frontend
    image: plugins/docker
    settings:
      repo: ktruckenmiller/docker-friend
      auto_tag: true
      target: FRIEND
      username:
        from_secret: username
      password:
        from_secret: password
      when:
        branch: [master]
        event: [push]

---
kind: pipeline
name: nginx

steps:
  - name: frontend
    image: plugins/docker
    settings:
      repo: ktruckenmiller/docker-friend-nginx
      auto_tag: true
      target: NGINX
      username:
        from_secret: username
      password:
        from_secret: password
      when:
        branch: [master]
        event: [push]
